import dbconfig
if dbconfig.dbhost=='localhost':
    beta_member_list = [
        ['gwyneth.bradbury@gmail.com',1]
    ]
else:
    beta_member_list = [
        ['gwyneth.bradbury@gmail.com',1],
        # ["quincy.vandenberg@physics.ox.ac.uk",1],
        # ["mlaw@jsl.co.nz",1],
        # ["silvia.butti@lincoln.ox.ac.uk",1]
    ]

is_member=2
is_comittee=1

real_member_list_done = [
        # ["Gwyneth.anne.dj@gmail.com",1],
    # ["Gwyneth.anne.dj@gmail.com",1],
    ["Aaliyah.wallace@merton.ox.ac.uk",is_member],
    ["Adamalradwan@gmail.com",is_member],
    ["Alec.Philip.matthews@gmail.com",is_member],
    ["Alp.katalan@stx.ox.ac.uk",is_member],
    ["amirahkaca@gmail.com",is_member],
    ["Amy.kiechle.mba22@said.oxford.edu",is_member],
    ["andrei.draghici@stcatz.ox.ac.uk",is_member],
    ["andres.vazquezbrennan@physics.ox.ac.uk",is_member],
    ["andrew.bolt314@gmail.com",is_member],
    ["annabellelucybuckland@hotmail.co.uk",is_member],
    ["benjiman.mclean@wadham.ox.ac.uk",is_member],
    ["Billy.weisskopf-sacre@exeter.ox.ac.uk",is_member],
    ["carlos.outeiral@stats.ox.ac.uk",is_member],
    ["Christiane.hagel@gtc.ox.ac.uk",is_member],
    ["daniel.ibanez@cardiov.ox.ac.uk",is_member],
    ["daniel.roade@sjc.ox.ac.uk",is_member],
    ["daniel.w.fraser@hotmail.com",is_member],
    ["deniz.ozguluk@new.ox.ac.uk",is_member],
    ["Dora.solloway@googlemail.com",is_member],
    ["dr.dragana.savich@gmail.com",is_member],
    ["Edie.abrahams@wadham.ox.ac.uk",is_member],
    ["Edmond.toma@chem.ox.ac.uk",is_member],
    ["ella.boot@trinity.ox.ac.uk",is_member],
    ["ellen.wright.dk@gmail.com",is_member],
    ["euger_29@hotmail.com",is_member],
    ["evie.holloway@yahoo.go.uk",is_member],
    ["filipokay@gmail.com",is_member],
    ["Frankie.wood123@gmail.com",is_member],
    ["jablevine@gmail.com",is_member],
    ["Grzegorz.komorowski@univ.ox.ac.uk",is_member],
    ["Jackrichardrvans@gmail.com",is_member],
    ["Jad.mounayer@outlook.com",is_member],
    ["Jake.simian@keble.ox.ac.uk",is_member],
    ["jamie.bolam@stx.ox.ac.uk",is_member],
    ["jberg321max@gmail.com",is_member],
    ["Jelani.allman@wadham.ox.ac.uk",is_member],
    [" jhmcdonnell@outlook.com",is_member],
    ["johannes.forkel@queens.ox.ac.uk",is_member],
    ["Jonathan.rystrom@bfriars.ox.ac.uk",is_member],
    ["jonathonliuau@gmail.com",is_member],
    ["justin.limkaichong@spc.ox.ac.uk",is_member],
    ["karma_singh007@hotmail.com",is_member],
    ["Kathrine.surgay@gmail.com",is_member],
    ["Kaya.axelsson@ouce.ox.ac.uk",is_member],
    ["Kbaez.dibujos@gmail.com",is_member],
    ["Kierri@hotmail.co.uk",is_member],
    ["klyde.gironella@wadham.ox.ac.uk",is_member],
    ["laura.dallecarbonare@biology.ox.ac.uk",is_member],
    ["leamallet@orange.fr",is_member],
    ["lilastewartroberts@gmail.com",is_member],
    ["Lindleybushnell@live.co.uk",is_member],
    ["Lisenklaksvik@gmail.com",is_member],
    ["ls.ahlborn@gmail.com",is_member],
    ["Lucy.scammell@stcatz.ox.ac.uk",is_member],
    ["luis.torada@linacre.ox.ac.uk",is_member],
    ["lushanyadayathilake@gmail.com",is_member],
    ["Madeleine.partland@lmh.ox.ac.uk",is_member],
    ["mahreen.khan@gmail.com ",is_member],
    ["marcin.konow@lczyk.xyz",is_member],
    ["marian.longa@gmail.com",is_member],
    ["Mariarb.cs@gmail.com ",is_member],
    ["mattdewsbury@live.com",is_member],
    ["Matthew.bowen@hertford.ox.ac.uk",is_member],
    ["Matthew@fides.me.uk",is_member],
    ["May.chemais@gmail.com",is_member],
    ["Michael.metzler@wolfson.ox.ac.uk",is_member],
    ["Michela.gramola@gmail.com",is_member],
    ["Minton27@gmail.com",is_member],
    ["mitchumbates@hotmail.com",is_member],
    ["monica.perri@seh.ox.ac.uk",is_member],
    ["mr_soltaninjd@yahoo.com",is_member],
    ["Ncrisp97@hotmail.co.uk",is_member],
    ["popovychviktoriia422@gmail.com",is_member],
    ["reno.domel@stx.ox.ac.uk",is_member],
    ["rob.odonoghue12@gmail.com",is_member],
    ["rosemaywyatt@yahoo.co.uk",is_member],
    ["Roworth123@btinternet.com",is_member],

    ]
real_member_list=[
    ["Rtknnd@gmail.com",is_member],
    ["SANT6034@OX.AC.UK",is_member],
    ["Scat9561@ox.ac.uk",is_member],
    ["seanjwest@outlook.com",is_member],
    ["Shiemaa.Ahmed@outlook.com",is_member],
    ["sophia.reidl@spc.ox.ac.uk",is_member],
    ["steve_n@gmx.com",is_member],
    ["Tea.ghigo@gmail.com",is_member],
    ["Temitope.a@live.it",is_member],
    ["thomas_redston@outlook.com",is_member],
    ["Tracey.roberts@theology.ox.ac.uk",is_member],
    ["Valen.yg@gmail.com",is_member],
    ["william.ludington@linacre.ox.ac.uk",is_member],
    ["wilzturner@gmail.com",is_member],
    ["ziatariq88@gmail.com",is_member],
    ["Zighizu@gmail.com",is_member],
    ["euger_29@hotmail.com",is_member],
    ]
not_yet=[
    ]