import dbconfig
if dbconfig.dbhost=='localhost':
    beta_member_list = [
        ['gwyneth.bradbury@gmail.com',1]
    ]
else:
    beta_member_list = [
        ['gwyneth.bradbury@gmail.com',1],
        ["quincy.vandenberg@physics.ox.ac.uk",1],
        ["mlaw@jsl.co.nz",1],
        ["silvia.butti@lincoln.ox.ac.uk",1]
    ]

real_member_list = [
        # ["Gwyneth.anne.dj@gmail.com",1],
        ["philip.torr@eng.ox.ac.uk",1],
        #
        ["richardpstrange@outlook.com",2],
        ["pauledoux@hotmail.com", 2],
        ["rowie_borst@hotmail.com",2],
        ["isabella.walker@gmail.com",2],
        ["g.shiroki@gmail.com",2],
        ["anna.spearing-ewyn@sjc.ox.ac.uk",2],
        ["tereza.miketa@gmail.com",2],
        ["alaskangirl_uk@yahoo.co.uk",2],
        ["esmefrances@hotmail.com",2],
        ["vero3guerin@hotmail.co.uk",2],
        ["kasprzak@stats.ox.ac.uk",2],
        ["f.falkhartelius@gmail.com",2],
        ["richard_3986@yahoo.co.uk",2],
        ["riva11306@gmail.com",2],
        ["weis@maths.ox.ac.uk",2],
        ["jordan.wheelybin@gmail.com",2],
        ["tahnee.oons@inet.ox.ac.uk",2],
        ["sophia.middlehurst@ssho.ox.ac.uk",2],
        ["christopher.mcgamy@merton.ox.ac.uk",2],
        ["julia.vassileva@worc@ox.ac.uk",2],
        ["tina.christman@worc.ox.ac.uk",2],
        ["alexandia.wuergler@stx.ox.ac.uk",2],
        ["raquel.alvram@gmail.com",2],
        ["belenaparrocho@hotmail.com",2],
        ["ioana.bica@emg.ox.ac.uk",2],
        ["michael.painter@pmb.ox.ac.uk",2],
        ["g.shiroki@gmail.com",2],
        ["thulgiathessa@gmail.com",2],
        ["jonathan.downing@gmail.com",2],
        ["lgmanya@live.co.uk",2],
        ["charlotte.burnell@hertford.ox.ac uk",2],
        ["robert.cortes@chch.ox.ac.uk",2],
        ["laurence.hutchence@wolfson.ax.ac.uk",2],
        ["christoph.hoeppre@sallicel.ox.ac.uk",2],
        ["zhizhou.xia@rsa.ox.ac.uk",2],
        ["eleonora.pilla@gmail.com",2],
        ["cecig2@hotmail.com",2],
        ["emily.ajgan@oriel.ox.ac.uk",2],
        ["caitlyn.kinsella@kellog.ox.ac.uk",2],
        ["joana.grigoras@sjc.ox.ac.uk",2],
        ["joanna.heyl@lmh.ox.ac.uk",2],
        ["Rayarigueras@gmail.com",2],
        ["samanta.fien-helteman@keble.ox.ac.uk",2],
        ["coloy@hotmail.com",2],
        ["anjali.shah@learning.ox.ac.uk",2],
        # ["jakub....",2],
        ["samuel.lippl@seh.ox.ac.uk",2],
        ["ele_jones@hotmail.co.uk",2],
        ["amyrachell@hotmail.co.uk",2],
        ["sergio.martiv@chch.ox.ac.uk",2],
        ["michael.hardman@lmh.ox.ac.uk",2],
        ["brandon.largey@linacre.ox.ac.uk",2],
        ["ojiromu.enukpere.mba18@said.oxford.edu",2],
        ["raghav.agarwal.mba18@said.oxford.edu",2],
        ["genevieve.horwood@gtc.ox.ac.uk",2],
        ["william.shardlow@new.ox.ac.uk",2],
        ["elena.ansbro@bnc.ox.ac.uk",2],
        ["caroline.lear@exeter.ox.ac.uk",2],
    ]